# Generated by Django 2.1.7 on 2019-03-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190317_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='macroelements',
            name='carbohydrats',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='macroelements',
            name='fat',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='macroelements',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
