# Generated by Django 2.1.7 on 2019-03-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190317_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Macroelements',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrats',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
